### ISSUE TITLE
替换规则后，手机连接wifi总提示连接开放网络，不知为何。

### ISSUE THREAD

**Issue by luvjojo** [ihuaer/koolproxy#1]
我是直接进路由器的koolshare文件夹里的Koolproxy文件夹里把rules里的文件直接替换使用的，广告能正常去掉，就是连接wifi时会一直提示连接开放网络的提示，请问有办法解决吗？还是说我替换的方法不对。

**Comment by ihuaer** [comment]
> 我是直接进路由器的koolshare文件夹里的Koolproxy文件夹里把rules里的文件直接替换使用的，广告能正常去掉，就是连接wifi时会一直提示连接开放网络的提示，请问有办法解决吗？还是说我替换的方法不对。

请确认是否安装证书和开启https过滤

**Comment by luvjojo** [comment]
没安装证书，访问控制力设置的是http only过滤

**Comment by ihuaer** [comment]
断开WiFi 忘记后，重新连、输入用户名密码

**Comment by babylife** [comment]
按理说这个和KP没有关系，其他手机有一样的问题吗？

**Comment by luvjojo** [comment]
> 按理说这个和KP没有关系，其他手机有一样的问题吗？

一样有，而且关闭kp后就不会
