### ISSUE TITLE
这个怎么安装啊 ，

### ISSUE THREAD

**Issue by fei98653201** [ihuaer/koolproxy#1]
用winscp链接路由器了  但是怎么卸载以前的koolproxy  安装这个新的呢    qq  273385854  期待您的解答

**Comment by ihuaer** [comment]
这个是自己用的过滤规则，不是新的koolproxy




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"爱折腾"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 中午1:42
收件人:&nbsp;"ihuaer/koolproxy"<koolproxy@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ihuaer/koolproxy] 这个怎么安装啊 ， (#1)





 
用winscp链接路由器了  但是怎么卸载以前的koolproxy  安装这个新的呢    qq  273385854  期待您的解答

**Comment by fei98653201** [comment]
能指导下我怎么安装这个吗？

**Comment by ihuaer** [comment]
如图所示，可以添加自己喜欢的过滤规则
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"爱折腾"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 中午11:15
收件人:&nbsp;"ihuaer/koolproxy"<koolproxy@noreply.github.com&gt;;
抄送:&nbsp;"larryzhu"<bo.z.zhu@gmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ihuaer/koolproxy] 这个怎么安装啊 ， (#1)





 
能指导下我怎么安装这个吗？

**Comment by ihuaer** [comment]
closed
