### ISSUE TITLE
已添加咪咕视频广告过滤

### ISSUE THREAD

**Issue by ihuaer** [ihuaer/koolproxy#2]
目前大多数视频网站采用https广告
需要安装证书
目前，安装证书最方便的就是ios设备，例如iPhone iPad  apple tv

**Comment by hliu4atomos** [comment]
请问apple tv怎么安装证书呢？ apple tv没有浏览器。

**Comment by ihuaer** [comment]
> 请问apple tv怎么安装证书呢？ apple tv没有浏览器。

参考这里
https://www.shuzhiduo.com/A/ke5jmEx9Jr/

**Comment by hliu4atomos** [comment]
多谢，多谢

**Comment by ihuaer** [comment]
closed
